"""
Exceptions module for the fortytwo package.
"""

from fortytwo.exceptions.exceptions import (
    FortyTwoAuthException,
    FortyTwoClientException,
    FortyTwoNetworkException,
    FortyTwoNotFoundException,
    FortyTwoParsingException,
    FortyTwoRateLimitException,
    FortyTwoRequestException,
    FortyTwoServerException,
    FortyTwoUnauthorizedException,
)


__all__ = [
    "FortyTwoAuthException",
    "FortyTwoClientException",
    "FortyTwoNetworkException",
    "FortyTwoNotFoundException",
    "FortyTwoParsingException",
    "FortyTwoRateLimitException",
    "FortyTwoRequestException",
    "FortyTwoServerException",
    "FortyTwoUnauthorizedException",
]
